// 徳之島 集落マスタ
// 出典: SPEC.md参照（徳之島町公式・伊仙町公式・Wikipedia天城町）
// x, y は地図SVG viewBox(0 0 100 120) に対する座標。デフォルメ地図上の近似位置
const TOWNS = {
  isen: "伊仙町",
  amagi: "天城町",
  tokunoshima: "徳之島町",
  all: "全島",
};

const VILLAGES = [
  // ===== 徳之島町（27）北から南へ =====
  { id: "tete",        name: "手々",   kana: "てて",       town: "tokunoshima", x: 42, y: 9 },
  { id: "kanami",      name: "金見",   kana: "かなみ",     town: "tokunoshima", x: 58, y: 10 },
  { id: "san",         name: "山",     kana: "さん",       town: "tokunoshima", x: 62, y: 16 },
  { id: "sansato",     name: "山里",   kana: "さんさと",   town: "tokunoshima", x: 56, y: 19 },
  { id: "uchikawa",    name: "内千川", kana: "うちかわ",   town: "tokunoshima", x: 52, y: 24 },
  { id: "aze",         name: "畦",     kana: "あぜ",       town: "tokunoshima", x: 68, y: 21 },
  { id: "todoroki",    name: "轟木",   kana: "とどろき",   town: "tokunoshima", x: 72, y: 26 },
  { id: "kedoku",      name: "花徳",   kana: "けどく",     town: "tokunoshima", x: 74, y: 32 },
  { id: "uekedoku",    name: "上花徳", kana: "うえけどく", town: "tokunoshima", x: 66, y: 31 },
  { id: "kedokina",    name: "花時名", kana: "けどきな",   town: "tokunoshima", x: 76, y: 37 },
  { id: "shinmura",    name: "新村",   kana: "しんむら",   town: "tokunoshima", x: 69, y: 37 },
  { id: "boma",        name: "母間",   kana: "ぼま",       town: "tokunoshima", x: 76, y: 42 },
  { id: "tankawa",     name: "反川",   kana: "たんかわ",   town: "tokunoshima", x: 66, y: 43 },
  { id: "oatari",      name: "大当",   kana: "おおあたり", town: "tokunoshima", x: 71, y: 46 },
  { id: "ikema",       name: "池間",   kana: "いけま",     town: "tokunoshima", x: 63, y: 49 },
  { id: "shimokushi",  name: "下久志", kana: "しもくし",   town: "tokunoshima", x: 78, y: 49 },
  { id: "inokawa",     name: "井之川", kana: "いのかわ",   town: "tokunoshima", x: 80, y: 55 },
  { id: "asahigaoka",  name: "旭ケ丘", kana: "あさひがおか", town: "tokunoshima", x: 73, y: 57 },
  { id: "shoda",       name: "諸田",   kana: "しょだ",     town: "tokunoshima", x: 78, y: 61 },
  { id: "kaminomine",  name: "神之嶺", kana: "かみのみね", town: "tokunoshima", x: 81, y: 64 },
  { id: "tokuwase",    name: "徳和瀬", kana: "とくわせ",   town: "tokunoshima", x: 82, y: 69 },
  { id: "kametoku",    name: "亀徳",   kana: "かめとく",   town: "tokunoshima", x: 83, y: 73 },
  { id: "kametsu",     name: "亀津",   kana: "かめつ",     town: "tokunoshima", x: 81, y: 79 },
  { id: "shirai",      name: "白井",   kana: "しらい",     town: "tokunoshima", x: 66, y: 60 },
  { id: "ohara",       name: "大原",   kana: "おおはら",   town: "tokunoshima", x: 71, y: 68 },
  { id: "nanbaru",     name: "南原",   kana: "なんばる",   town: "tokunoshima", x: 68, y: 74 },
  { id: "omo",         name: "尾母",   kana: "おも",       town: "tokunoshima", x: 66, y: 80 },

  // ===== 天城町（11）北から南へ =====
  { id: "yonama",      name: "与名間", kana: "よなま",     town: "amagi", x: 30, y: 10 },
  { id: "matsubara",   name: "松原",   kana: "まつばら",   town: "amagi", x: 24, y: 17 },
  { id: "amagi",       name: "天城",   kana: "あまぎ",     town: "amagi", x: 26, y: 24 },
  { id: "okazen",      name: "岡前",   kana: "おかぜん",   town: "amagi", x: 24, y: 30 },
  { id: "hetono",      name: "平土野", kana: "へとの",     town: "amagi", x: 18, y: 34 },
  { id: "asama",       name: "浅間",   kana: "あさま",     town: "amagi", x: 20, y: 41 },
  { id: "kaneku",      name: "兼久",   kana: "かねく",     town: "amagi", x: 17, y: 48 },
  { id: "setaki",      name: "瀬滝",   kana: "せたき",     town: "amagi", x: 19, y: 55 },
  { id: "tobe",        name: "当部",   kana: "とうべ",     town: "amagi", x: 30, y: 52 },
  { id: "otsukawa",    name: "大津川", kana: "おおつかわ", town: "amagi", x: 20, y: 62 },
  { id: "nishiagina",  name: "西阿木名", kana: "にしあぎな", town: "amagi", x: 23, y: 69 },

  // ===== 伊仙町（20）西から東へ =====
  { id: "inutabu",     name: "犬田布", kana: "いぬたぶ",   town: "isen", x: 28, y: 80 },
  { id: "kinoko",      name: "木之香", kana: "きのこ",     town: "isen", x: 33, y: 75 },
  { id: "asan-shikaura", name: "阿三・鹿浦", kana: "あさん・しかうら", town: "isen", x: 35, y: 87 },
  { id: "agon",        name: "阿権",   kana: "あごん",     town: "isen", x: 39, y: 81 },
  { id: "kawachi",     name: "河地",   kana: "かわち",     town: "isen", x: 41, y: 70 },
  { id: "sagibaru",    name: "崎原",   kana: "さぎばる",   town: "isen", x: 46, y: 73 },
  { id: "kojima",      name: "小島",   kana: "こじま",     town: "isen", x: 44, y: 90 },
  { id: "itokina",     name: "糸木名", kana: "いときな",   town: "isen", x: 49, y: 78 },
  { id: "bane",        name: "馬根",   kana: "ばね",       town: "isen", x: 53, y: 71 },
  { id: "uebaru",      name: "上晴",   kana: "うえばる",   town: "isen", x: 57, y: 75 },
  { id: "nakayama",    name: "中山",   kana: "なかやま",   town: "isen", x: 51, y: 84 },
  { id: "isen",        name: "伊仙",   kana: "いせん",     town: "isen", x: 55, y: 88 },
  { id: "kenbuku",     name: "検福",   kana: "けんぶく",   town: "isen", x: 60, y: 82 },
  { id: "gozendo",     name: "御前堂", kana: "ごぜんどう", town: "isen", x: 59, y: 92 },
  { id: "omonawa",     name: "面縄",   kana: "おもなわ",   town: "isen", x: 63, y: 93 },
  { id: "furusato",    name: "古里",   kana: "ふるさと",   town: "isen", x: 49, y: 93 },
  { id: "meteku",      name: "目手久", kana: "めてぐ",     town: "isen", x: 68, y: 90 },
  { id: "yaezo",       name: "八重竿", kana: "やえぞう",   town: "isen", x: 64, y: 85 },
  { id: "saben",       name: "佐弁",   kana: "さべん",     town: "isen", x: 72, y: 87 },
  { id: "kinen",       name: "喜念",   kana: "きねん",     town: "isen", x: 75, y: 84 },
];
